name: spectrum
description: Project Cambridge

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: '1.4.0'

flutter:
  uses-material-design: true
  assets:
    - assets/google.scr
    - roms/48.rom