name: spectrum
description: Project Cambridge

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: '1.4.0'

flutter:
  uses-material-design: true
  assets:
    - assets/blank.jpg
    - assets/google.scr
    - roms/48.rom