name: spectrum
description: Project Cambridge

dependencies:
  flutter:
    sdk: flutter
  image: ^2.0.7
  scoped_model: "^1.0.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/blank.jpg
    - assets/google.scr
    - roms/48.rom