name: spectrum
description: Library providing the common components of the ZX Spectrum.
version: 0.9.2
author: Tim Sneath <tim@sneath.org>

environment:
  sdk: '>=2.0.0-dev.63.0 <3.0.0'

dev_dependencies:
  test: "^1.2.0"