name: spectrum
description: Project Cambridge
version: 1.0.0

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: '^1.8.0+1'
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/google.scr
    - roms/48.rom
    - roms/snapshots/JETSET.SNA
  fonts:
    - family: Source Code Pro
      fonts:
        - asset: assets/SourceCodePro-Regular.ttf